### ISSUE TITLE
How to zoom a canvas?

### ISSUE THREAD

**Issue by IvyGongoogle** [craigfrancis/zoomify#5]
Hello, sorry to trouble you again. I want to use your `zoomify` to zoom a `canvas`. I find the zoom function does not work in my [code](https://github.com/IvyGongoogle/zoomify).  Can you give some advises?
Like last time, you need click the original image to enlarge it in a new window.
Thank you very much~

**Comment by craigfrancis** [comment]
Sorry to say, but there are a few issues with this...

---

First, you changed the ID of the large image (was `image-zoom`, now `myCanvas-zoom`).

So the following CSS rule needs to be changed, otherwise the canvas won't be relatively positioned.

    diff zoomify.css
    <    .js-enabled #image-zoom-wrapper #image-zoom {
    ---
    >    .js-enabled #image-zoom-wrapper #myCanvas-zoom {

---

Second, where I was using an `<img>`, I changed it's size with `img_ref.width`.

But you can't do this on a canvas, as "[the bitmap and any associated contexts must be cleared back to their initial state](https://dev.w3.org/html5/spec-preview/the-canvas-element.html)".

So we have to use `img_ref.style.width` instead:

    diff zoomify.js
    <    img_ref.width      = img_current_width;
    <    img_ref.height     = img_current_height;
    ---
    >    img_ref.style.width  = img_current_width + 'px'; // Canvas element will reset any bitmap data when using img_ref.width
    >    img_ref.style.height = img_current_height + 'px';

---

Third, you can't create your `img_buffer`, set the `src`, and immediately get the width/height.

It takes some time for the image to be loaded (even from the cache).

That said, we do already have this image on the page (as `sourceImg`), and it has probably loaded by now (otherwise the user wouldn't click on it), so we can take it's width/height:

    diff zoomify.js
    <    var img_buffer = document.createElement('img');
    <    var src=document.getElementById("img-enlarge").getAttribute("src")
    <    img_buffer.src=src
    <    var imgWidth=img_buffer.width;
    <    var imgHeight=img_buffer.height;
    ---
    >    var src=sourceImg.getAttribute("src")
    >    var imgWidth=sourceImg.width;
    >    var imgHeight=sourceImg.height;

---

That said, because we already have the `<img>` on the page already (as `sourceImg`), we don't need to create a `new Image()`:

    diff zoomify.js
    <    var img = new Image();
    <    img.src = src
    <    ctx.drawImage(img, 0, 0, imgWidth, imgHeight);
    ---
    >    ctx.drawImage(sourceImg, 0, 0, imgWidth, imgHeight);

---

And finally, the `init()` function needs to know what the image width/height will be.

So where you currently have it just after `captionText`, it should be moved towards the end of your `click` function, maybe just after the `ctx.drawImage()`?
